### ISSUE TITLE
Change `license` value in package.json to match LICENSE file contents

### ISSUE THREAD

**Issue by Fdawgs** [mwilliamson/duck.js#1]
It looks like the [license file](https://github.com/mwilliamson/duck.js/blob/master/LICENSE) in this repo is using the BSD 2-Clause "Simplified" License, which has an [spdx identifier](https://spdx.org/licenses/BSD-2-Clause.html) of "BSD-2-Clause", not "BSD" as it is currently set in package.json:

https://github.com/mwilliamson/duck.js/blob/6e342b5447b157dd265b1bba7bb915e2dfeb3560/package.json#L6

This mismatch is being flagged up by license checking tools like license-checker.

**Comment by mwilliamson** [comment]
Done, thanks for the report.
